---
name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  type-check:
    runs-on: ubuntu-latest
    env:
      NVIM_APPNAME: "tiny.nvim"
      TINY_NVIM_CI: "1"
    strategy:
      matrix:
        neovim-version: [stable, nightly]
    steps:
      - uses: actions/checkout@v7

      - name: Set XDG_CONFIG_HOME
        run: echo "XDG_CONFIG_HOME=$(dirname "$GITHUB_WORKSPACE")" >> "$GITHUB_ENV"

      - name: Setup PATH
        run: mkdir -p "$HOME/.local/bin"

      - name: Install nvim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim-version }}

      - name: Print neovim version
        run: nvim -V1 -v

      - name: Install emmylua_check
        run: |
          gh release download -R EmmyLuaLs/emmylua-analyzer-rust "$EMMYLUA_VERSION" -p "$EMMYLUA_ASSET"
          tar -xf "$EMMYLUA_ASSET"
          mv ./emmylua_check "$HOME/.local/bin"
        env:
          EMMYLUA_VERSION: "0.25.1"
          EMMYLUA_ASSET: "emmylua_check-linux-x64-glibc.2.17.tar.gz"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print emmylua_check version
        run: emmylua_check -V

      - name: Install nvim plugins
        run: nvim --headless +qa

      - name: Type check
        run: ./scripts/type-check.sh
